package com.yoyo.privatechat;
import android.content.*;import android.os.*;import okhttp3.*;import org.json.*;import java.util.*;import java.util.concurrent.*;import java.time.*;
public final class Api{
 public static final String BASE="https://ivjqorxkqnipyelnjlqp.supabase.co",KEY="sb_publishable_nplKway4Sl6M39aa3jjSkA_oqjlOGBA";
 public static final OkHttpClient HTTP=new OkHttpClient.Builder().connectTimeout(15,TimeUnit.SECONDS).readTimeout(25,TimeUnit.SECONDS).pingInterval(25,TimeUnit.SECONDS).build();static final ExecutorService pool=Executors.newSingleThreadExecutor();static final Handler main=new Handler(Looper.getMainLooper());public interface Work{void run()throws Exception;}public interface Done{void done(String error);}
 public static void job(Work w,Done d){pool.execute(()->{String e=null;try{w.run();}catch(Exception ex){e=ex.getMessage();if(e==null)e="تعذر الاتصال بالخدمة";}final String err=e;main.post(()->{if(d!=null)d.done(err);});});}
 public static String request(Context c,String path,String method,Object body,boolean auth)throws Exception{if(auth)refresh(c);Request.Builder b=new Request.Builder().url(BASE+path).header("apikey",KEY).header("Prefer","return=representation");if(auth)b.header("Authorization","Bearer "+Prefs.get(c,"token"));if(method.equals("GET"))b.get();else b.method(method,RequestBody.create(body==null?"":body.toString(),MediaType.parse("application/json")));try(Response r=HTTP.newCall(b.build()).execute()){String s=r.body()==null?"":r.body().string();if(!r.isSuccessful()){String err="تعذر الاتصال ("+r.code()+")";try{JSONObject j=new JSONObject(s);err=j.optString("error_description",j.optString("error",j.optString("message",err)));}catch(Exception e){}throw new Exception(err);}return s;}}
 public static synchronized void refresh(Context c)throws Exception{long exp=0;try{exp=Long.parseLong(Prefs.get(c,"expires"));}catch(Exception e){}if(exp<System.currentTimeMillis()+90000){if(Prefs.get(c,"refresh").isEmpty())throw new Exception("سجّل الدخول أولاً");Prefs.session(c,new JSONObject(request(c,"/auth/v1/token?grant_type=refresh_token","POST",new JSONObject().put("refresh_token",Prefs.get(c,"refresh")),false)));}}
 public static void login(Context c,String user,String pass)throws Exception{JSONObject b=new JSONObject().put("email",user.trim().toLowerCase(Locale.ROOT)+"@yoyo-native.invalid").put("password",pass);Prefs.session(c,new JSONObject(request(c,"/auth/v1/token?grant_type=password","POST",b,false)));JSONArray rows=new JSONArray(request(c,"/rest/v1/yoyo_native_profiles?id=eq."+Prefs.phone(c),"GET",null,true));if(rows.length()!=1){Prefs.clear(c);throw new Exception("هذا الحساب غير مسجل في يويو");}JSONObject me=rows.getJSONObject(0);if(!me.getString("public_key").equals(CryptoBox.publicKey())){Prefs.clear(c);throw new Exception("الحساب مرتبط بجهازه الأصلي؛ يلزم نقل مفاتيح الجهاز قبل الدخول من جهاز جديد");}Prefs.put(c,"name",me.getString("name"));Prefs.put(c,"avatar",me.optString("avatar"));Prefs.put(c,"username",me.getString("username"));contacts(c);}
 public static void register(Context c,String user,String pass,String name,String invite)throws Exception{request(c,"/functions/v1/yoyo-native-register","POST",new JSONObject().put("username",user).put("password",pass).put("name",name).put("invite",invite).put("public_key",CryptoBox.publicKey()),false);login(c,user,pass);}
 public interface EntryDone{void done(String field,String error);}
 public static void entry(Context c,String name,String password,String invite,EntryDone done){entry(c,name,password,invite,false,done);}
 public static void entry(Context c,String name,String password,String invite,boolean recover,EntryDone done){pool.execute(()->{String field="general",error=null;try{
  JSONObject body=new JSONObject().put("name",name).put("password",password).put("invite",invite).put("recover",recover).put("public_key",CryptoBox.publicKey());
  Request req=new Request.Builder().url(BASE+"/functions/v1/yoyo-native-entry").header("apikey",KEY).post(RequestBody.create(body.toString(),MediaType.parse("application/json"))).build();
  try(Response response=HTTP.newCall(req).execute()){JSONObject data=new JSONObject(response.body()==null?"{}":response.body().string());
   if(!response.isSuccessful()){field=data.optString("field","general");error=data.optString("error","تعذر الدخول؛ حاول مجددًا");}
   else{JSONObject profile=data.getJSONObject("profile");Prefs.session(c,data.getJSONObject("session"));Prefs.put(c,"name",profile.getString("name"));Prefs.put(c,"avatar",profile.optString("avatar"));Prefs.put(c,"username",profile.getString("username"));Prefs.put(c,"slot",String.valueOf(profile.getInt("slot")));Prefs.put(c,"login_name",name.trim());Prefs.put(c,"self_profile",profile.toString());}
  }
 }catch(java.io.IOException e){error="تعذر الاتصال بالإنترنت. تأكد من الشبكة وحاول مجددًا.";}catch(Exception e){error="تعذر الدخول. أغلق التطبيق وافتحه مجددًا ثم حاول.";}
 final String f=field,err=error;main.post(()->done.done(f,err));});}
 public static void contacts(Context c)throws Exception{applyContacts(c,new JSONArray(request(c,"/rest/v1/yoyo_native_profiles?order=slot","GET",null,true)));}
 static void applyContacts(Context c,JSONArray a)throws Exception{
  JSONArray out=new JSONArray();boolean pending=false;
  for(int i=0;i<a.length();i++){JSONObject p=a.getJSONObject(i);String id=p.getString("id");
   if(id.equals(Prefs.phone(c))){if(!p.getString("public_key").equals(CryptoBox.publicKey()))throw new SecurityException("تم استرجاع الحساب على تثبيت آخر. سجّل الدخول مجددًا إذا أردت نقله إلى هنا.");Prefs.put(c,"self_profile",p.toString());continue;}
   String pin=Prefs.get(c,"key_"+id),key=p.getString("public_key");
   if(!pin.isEmpty()&&!pin.equals(key)){Prefs.put(c,"pending_key_"+id,p.toString());pending=true;JSONObject old=EventStore.contact(c,id);if(old.has("id"))out.put(old);}
   else{Prefs.put(c,"key_"+id,key);Prefs.put(c,"pending_key_"+id,"");out.put(p);}
  }
  Prefs.put(c,"contacts",out.toString());if(pending){changed(c);throw new SecurityException("تغيّر جهاز أحد الحسابات. افتح يويو واضغط مراجعة تغيير الجهاز.");}
 }
 static void acceptContactKey(Context c,JSONObject reviewed)throws Exception{
  String id=reviewed.getString("id");JSONObject pending=new JSONObject(Prefs.get(c,"pending_key_"+id));
  if(!pending.getString("public_key").equals(reviewed.getString("public_key")))throw new SecurityException("تغيّر الجهاز مجددًا. راجع التنبيه الجديد.");
  Prefs.put(c,"key_"+id,reviewed.getString("public_key"));Prefs.put(c,"pending_key_"+id,"");
 }
 public static JSONObject base(Context c,String to,String type)throws Exception{return new JSONObject().put("id",UUID.randomUUID().toString()).put("from",Prefs.phone(c)).put("to",to).put("type",type).put("ts",System.currentTimeMillis());}
 public static void send(Context c,JSONObject plain)throws Exception{String outgoingType=plain.getString("type");if(outgoingType.equals("chat")||outgoingType.equals("story")||outgoingType.equals("call_offer"))contacts(c);if(!Prefs.get(c,"pending_key_"+plain.getString("to")).isEmpty())throw new SecurityException("راجع تغيير جهاز الشخص الآخر قبل الاتصال أو الإرسال");JSONObject target=EventStore.contact(c,plain.getString("to"));if(target.optString("public_key").isEmpty())throw new Exception("الحساب الآخر غير موجود بعد");String type=plain.getString("type");JSONObject e=new JSONObject().put("id",plain.getString("id")).put("sender",Prefs.phone(c)).put("recipient",plain.getString("to")).put("kind",type).put("payload",CryptoBox.seal(c,plain,plain.getString("to"),target.getString("public_key")));if(!type.equals("chat")){long expiry=System.currentTimeMillis()+(type.equals("story")?86300000:170000);e.put("expires_at",Instant.ofEpochMilli(expiry).toString());plain.put("expires",expiry);}request(c,"/rest/v1/yoyo_native_events","POST",e,true);plain.put("status","sent");if(type.equals("chat")||type.equals("story"))EventStore.get(c).save(c,plain);changed(c);}
 public static void sync(Context c,boolean initial)throws Exception{contacts(c);String cursor=Prefs.get(c,"cursor"),from=cursor,path="/rest/v1/yoyo_native_events?order=created_at.asc,id.asc&limit=100";if(!cursor.isEmpty())try{from=Instant.parse(cursor).minusSeconds(600).toString();}catch(Exception ignored){}if(!from.isEmpty())path+="&created_at=gte."+java.net.URLEncoder.encode(from,"UTF-8");int offset=0;String newest=cursor;while(true){JSONArray a=new JSONArray(request(c,path+"&offset="+offset,"GET",null,true));for(int i=0;i<a.length();i++){JSONObject e=a.getJSONObject(i);try{ingest(c,e,!initial);}catch(Exception bad){report(c,"ingest",bad,e.optString("id"));String kind=e.optString("kind");if(kind.equals("chat")&&!e.optString("sender").equals(Prefs.phone(c))&&!EventStore.get(c).exists(e.optString("id"))){JSONObject unavailable=new JSONObject().put("id",e.getString("id")).put("from",e.getString("sender")).put("to",e.getString("recipient")).put("type","chat").put("ts",Instant.parse(e.getString("created_at")).toEpochMilli()).put("unavailable",true).put("status","unavailable").put("text","تعذر فتح هذه الرسالة. حدّثوا يويو للطرفين وأعيدوا إرسالها.");EventStore.get(c).save(c,unavailable);}}String t=e.optString("created_at");if(!t.isEmpty())try{if(newest.isEmpty()||Instant.parse(t).isAfter(Instant.parse(newest)))newest=t;}catch(Exception ignored){newest=t;}}if(a.length()<100)break;offset+=100;}if(!newest.isEmpty())Prefs.put(c,"cursor",newest);request(c,"/rest/v1/yoyo_native_profiles?id=eq."+Prefs.phone(c),"PATCH",new JSONObject().put("last_seen",Instant.now().toString()),true);changed(c);}
 public static void ingest(Context c,JSONObject e,boolean notify)throws Exception{String from=e.getString("sender"),type=e.getString("kind"),id=e.getString("id");boolean own=from.equals(Prefs.phone(c));String key=own?CryptoBox.publicKey():EventStore.contact(c,from).optString("public_key");if(key.isEmpty()){contacts(c);key=EventStore.contact(c,from).optString("public_key");}JSONObject signer=own?new JSONObject(Prefs.get(c,"self_profile")):EventStore.contact(c,from);
 JSONObject p;try{p=decodeEvent(c,e,key,signer);}
 catch(CryptoBox.UnavailableKeyException lost){
  if(type.equals("chat")&&!EventStore.get(c).exists(id)){
   JSONObject unavailable=new JSONObject().put("id",id).put("from",from).put("to",e.getString("recipient")).put("type","chat").put("ts",Instant.parse(e.getString("created_at")).toEpochMilli()).put("unavailable",true).put("status","unavailable").put("text","رسالة قديمة لا يمكن فتحها بعد استرجاع الحساب. اطلب إعادة إرسالها.");
   EventStore.get(c).save(c,unavailable);try{request(c,"/rest/v1/yoyo_native_events?id=eq."+id,"PATCH",new JSONObject().put("delivered",true),true);}catch(Exception ignored){}changed(c);
  }return;
 }if(!from.equals(p.getString("from"))||!id.equals(p.getString("id"))||!e.getString("recipient").equals(p.getString("to"))||!type.equals(p.getString("type")))throw new SecurityException("بيانات غير متطابقة");p.put("status",e.optBoolean("seen")?"read":e.optBoolean("delivered")?"delivered":"sent");p.put("ts",Instant.parse(e.getString("created_at")).toEpochMilli());if(type.equals("story"))p.put("expires",Instant.parse(e.getString("expires_at")).toEpochMilli());if(type.equals("chat")||type.equals("story")){boolean fresh=EventStore.get(c).save(c,p);if(!own&&fresh&&notify&&type.equals("chat"))RealtimeService.message(c,p);if(!own&&type.equals("chat")&&!e.optBoolean("delivered"))request(c,"/rest/v1/yoyo_native_events?id=eq."+id,"PATCH",new JSONObject().put("delivered",true),true);changed(c);}else if(!own&&System.currentTimeMillis()-p.optLong("ts")<170000){String cid=p.optString("callId");if(!cid.isEmpty()){List<String> q=RealtimeService.signals.computeIfAbsent(cid,k->Collections.synchronizedList(new ArrayList<>()));if(q.size()<100)q.add(p.toString());}if(type.equals("call_hangup"))((android.app.NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE)).cancel(9001);c.sendBroadcast(new Intent(RealtimeService.ACTION_EVENT).setPackage(c.getPackageName()).putExtra("json",p.toString()));if(type.equals("call_offer"))RealtimeService.incoming(c,p);}}
 static JSONObject decodeEvent(Context c,JSONObject e,String key,JSONObject signer)throws Exception{
  try{return CryptoBox.openWithHistory(c,e.getString("payload"),key,signer.optJSONArray("key_history"),e.getString("created_at"));}
  catch(SecurityException invalid){boolean own=e.getString("sender").equals(Prefs.phone(c));JSONObject refreshed;if(own)refreshed=new JSONObject(Prefs.get(c,"self_profile"));else{JSONArray rows=new JSONArray(request(c,"/rest/v1/yoyo_native_profiles?id=eq."+e.getString("sender"),"GET",null,true));if(rows.length()!=1)throw invalid;refreshed=rows.getJSONObject(0);}return CryptoBox.openWithHistory(c,e.getString("payload"),refreshed.getString("public_key"),refreshed.optJSONArray("key_history"),e.getString("created_at"));}
 }
 static void report(Context c,String stage,Exception ex,String eventId){try{request(c,"/rest/v1/yoyo_native_client_errors","POST",new JSONObject().put("user_id",Prefs.phone(c)).put("stage",stage).put("event_id",eventId).put("error",ex.getClass().getSimpleName()+": "+String.valueOf(ex.getMessage())).put("app_version","0.3.4"),true);}catch(Exception ignored){}}
 public static void changed(Context c){c.sendBroadcast(new Intent(RealtimeService.ACTION_EVENT).setPackage(c.getPackageName()));}public static void profile(Context c,String name,String avatar)throws Exception{request(c,"/rest/v1/yoyo_native_profiles?id=eq."+Prefs.phone(c),"PATCH",new JSONObject().put("name",name).put("avatar",avatar),true);Prefs.put(c,"name",name);Prefs.put(c,"avatar",avatar);}
}
