package com.yoyo.privatechat;
import android.content.Context;import android.security.keystore.*;import android.util.Base64;import java.security.*;import java.security.spec.*;import javax.crypto.*;import javax.crypto.spec.*;import org.json.*;
public final class CryptoBox{
 private static final String ALIAS="yoyo_device_v2";
 static String b64(byte[] b){return Base64.encodeToString(b,Base64.NO_WRAP);}static byte[] bytes(String s){return Base64.decode(s,Base64.DEFAULT);}
 static KeyStore store()throws Exception{KeyStore k=KeyStore.getInstance("AndroidKeyStore");k.load(null);return k;}
 public static String publicKey()throws Exception{KeyStore k=store();if(!k.containsAlias(ALIAS)){KeyPairGenerator g=KeyPairGenerator.getInstance("RSA","AndroidKeyStore");g.initialize(new KeyGenParameterSpec.Builder(ALIAS,KeyProperties.PURPOSE_DECRYPT|KeyProperties.PURPOSE_SIGN).setKeySize(2048).setDigests(KeyProperties.DIGEST_SHA256,KeyProperties.DIGEST_SHA512).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_RSA_OAEP).setSignaturePaddings(KeyProperties.SIGNATURE_PADDING_RSA_PKCS1).build());g.generateKeyPair();}return b64(store().getCertificate(ALIAS).getPublicKey().getEncoded());}
 static PublicKey pub(String s)throws Exception{return KeyFactory.getInstance("RSA").generatePublic(new X509EncodedKeySpec(bytes(s)));}
 static Cipher rsa(int mode,Key k)throws Exception{Cipher c=Cipher.getInstance("RSA/ECB/OAEPPadding");c.init(mode,k,new OAEPParameterSpec("SHA-256","MGF1",MGF1ParameterSpec.SHA1,PSource.PSpecified.DEFAULT));return c;}
 static byte[] wrap256(byte[] raw,PublicKey k)throws Exception{Cipher c=Cipher.getInstance("RSA/ECB/OAEPPadding");c.init(Cipher.ENCRYPT_MODE,k,new OAEPParameterSpec("SHA-256","MGF1",MGF1ParameterSpec.SHA256,PSource.PSpecified.DEFAULT));return c.doFinal(raw);}
 static byte[] unwrap(byte[] enc,PrivateKey k)throws Exception{
  Exception first=null;
  try{return rsa(Cipher.DECRYPT_MODE,k).doFinal(enc);}catch(Exception e){first=e;}
  try{Cipher c=Cipher.getInstance("RSA/ECB/OAEPWithSHA-256AndMGF1Padding");c.init(Cipher.DECRYPT_MODE,k);return c.doFinal(enc);}catch(Exception ignored){}
  throw first==null?new GeneralSecurityException("RSA unwrap failed"):first;
 }
 static byte[] unwrap256(byte[] enc,PrivateKey k)throws Exception{Cipher c=Cipher.getInstance("RSA/ECB/OAEPPadding");c.init(Cipher.DECRYPT_MODE,k,new OAEPParameterSpec("SHA-256","MGF1",MGF1ParameterSpec.SHA256,PSource.PSpecified.DEFAULT));return c.doFinal(enc);}
 public static String seal(Context c,JSONObject plain,String otherId,String otherKey)throws Exception{KeyGenerator g=KeyGenerator.getInstance("AES");g.init(256);SecretKey aes=g.generateKey();Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.ENCRYPT_MODE,aes);JSONObject o=new JSONObject();o.put("iv",b64(cipher.getIV()));o.put("ct",b64(cipher.doFinal(plain.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8))));JSONObject keys=new JSONObject(),keys256=new JSONObject();PublicKey self=pub(publicKey()),other=pub(otherKey);keys.put(Prefs.phone(c),b64(rsa(Cipher.ENCRYPT_MODE,self).doFinal(aes.getEncoded())));keys.put(otherId,b64(rsa(Cipher.ENCRYPT_MODE,other).doFinal(aes.getEncoded())));try{keys256.put(Prefs.phone(c),b64(wrap256(aes.getEncoded(),self)));keys256.put(otherId,b64(wrap256(aes.getEncoded(),other)));o.put("keys256",keys256);}catch(Exception ignored){}o.put("keys",keys);String body=o.toString();Signature s=Signature.getInstance("SHA256withRSA");s.initSign((PrivateKey)store().getKey(ALIAS,null));s.update(body.getBytes(java.nio.charset.StandardCharsets.UTF_8));return new JSONObject().put("body",body).put("signature",b64(s.sign())).toString();}
 static final class UnavailableKeyException extends GeneralSecurityException {UnavailableKeyException(Throwable t){super("Message uses an unavailable device key",t);}}
 public static JSONObject open(Context c,String payload,String senderKey)throws Exception{return openWithHistory(c,payload,senderKey,null,null);}
 static boolean verify(String body,String sig,String key)throws Exception{Signature v=Signature.getInstance("SHA256withRSA");v.initVerify(pub(key));v.update(body.getBytes(java.nio.charset.StandardCharsets.UTF_8));return v.verify(bytes(sig));}
 static void verifyWithHistory(String body,String sig,String current,JSONArray history,String createdAt)throws Exception{if(verify(body,sig,current))return;if(history!=null&&createdAt!=null)for(int i=0;i<history.length();i++){JSONObject h=history.getJSONObject(i);if(!java.time.Instant.parse(createdAt).isAfter(java.time.Instant.parse(h.getString("retired_at")))&&verify(body,sig,h.getString("public_key")))return;}throw new SecurityException("Bad signature");}
 public static JSONObject openWithHistory(Context c,String payload,String senderKey,JSONArray history,String createdAt)throws Exception{return openForKey(payload,senderKey,history,createdAt,Prefs.phone(c),(PrivateKey)store().getKey(ALIAS,null));}
 static JSONObject openForKey(String payload,String senderKey,JSONArray history,String createdAt,String id,PrivateKey privateKey)throws Exception{JSONObject e=new JSONObject(payload);String body=e.getString("body");verifyWithHistory(body,e.getString("signature"),senderKey,history,createdAt);JSONObject o=new JSONObject(body);byte[] key=null;Exception failure=null;try{key=unwrap(bytes(o.getJSONObject("keys").getString(id)),privateKey);}catch(Exception ex){failure=ex;}if(key==null&&o.has("keys256"))try{key=unwrap256(bytes(o.getJSONObject("keys256").getString(id)),privateKey);}catch(Exception ex){failure=ex;}if(key==null)throw new UnavailableKeyException(failure);Cipher d=Cipher.getInstance("AES/GCM/NoPadding");d.init(Cipher.DECRYPT_MODE,new SecretKeySpec(key,"AES"),new GCMParameterSpec(128,bytes(o.getString("iv"))));return new JSONObject(new String(d.doFinal(bytes(o.getString("ct"))),java.nio.charset.StandardCharsets.UTF_8));}
}
