package com.yoyo.privatechat;
import android.content.*;import android.database.*;import android.database.sqlite.*;import org.json.*;import java.util.*;
public final class EventStore extends SQLiteOpenHelper{
 private static EventStore db;public static synchronized EventStore get(Context c){if(db==null)db=new EventStore(c.getApplicationContext());return db;}private EventStore(Context c){super(c,"yoyo-native.db",null,1);}public void onCreate(SQLiteDatabase d){d.execSQL("create table events(id text primary key,owner text,peer text,kind text,ts integer,json text)");d.execSQL("create index ev_peer on events(owner,peer,ts)");}public void onUpgrade(SQLiteDatabase d,int a,int b){}
 public synchronized boolean save(Context c,JSONObject o){try{String me=Prefs.phone(c);String peer=me.equals(o.getString("from"))?o.getString("to"):o.getString("from");boolean fresh=!exists(o.getString("id"));ContentValues v=new ContentValues();v.put("id",o.getString("id"));v.put("owner",me);v.put("peer",peer);v.put("kind",o.getString("type"));v.put("ts",o.optLong("ts",System.currentTimeMillis()));v.put("json",o.toString());getWritableDatabase().insertWithOnConflict("events",null,v,SQLiteDatabase.CONFLICT_REPLACE);return fresh;}catch(Exception e){return false;}}
 public synchronized boolean exists(String id){try(Cursor q=getReadableDatabase().rawQuery("select 1 from events where id=?",new String[]{id})){return q.moveToFirst();}}
 public synchronized void updateStatus(Context c,String id,boolean delivered,boolean seen){try(Cursor q=getReadableDatabase().query("events",new String[]{"json"},"id=? and owner=?",new String[]{id,Prefs.phone(c)},null,null,null)){if(!q.moveToFirst())return;JSONObject o=new JSONObject(q.getString(0));o.put("status",seen?"read":delivered?"delivered":"sent");ContentValues v=new ContentValues();v.put("json",o.toString());getWritableDatabase().update("events",v,"id=? and owner=?",new String[]{id,Prefs.phone(c)});}catch(Exception ignored){}}
 public synchronized List<JSONObject> list(Context c,String peer,String kind){ArrayList<JSONObject> r=new ArrayList<>();String where="owner=? and kind=?";ArrayList<String> a=new ArrayList<>(Arrays.asList(Prefs.phone(c),kind));if(peer!=null){where+=" and peer=?";a.add(peer);}try(Cursor q=getReadableDatabase().query("events",new String[]{"json"},where,a.toArray(new String[0]),null,null,"ts asc")){while(q.moveToNext())try{JSONObject o=new JSONObject(q.getString(0));if(!kind.equals("story")||o.optLong("expires")>System.currentTimeMillis())r.add(o);}catch(Exception e){}}return r;}
 public static JSONArray contacts(Context c){try{return new JSONArray(Prefs.get(c,"contacts"));}catch(Exception e){return new JSONArray();}}public static JSONObject contact(Context c,String id){JSONArray a=contacts(c);for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&id.equals(o.optString("id")))return o;}return new JSONObject();}
}
