package com.yoyo.privatechat;
import android.app.*;import android.content.*;import android.content.pm.ServiceInfo;import android.media.*;import android.os.*;import androidx.core.app.NotificationCompat;import androidx.core.content.ContextCompat;import okhttp3.*;import org.json.*;import java.util.*;
public class RealtimeService extends Service{
 public static final String ACTION_EVENT="com.yoyo.privatechat.EVENT",EXTRA_JSON="json";public static volatile boolean connected=false;public static volatile String openChat="",activeCall="",activePeer="";public static volatile boolean activeOutgoing=false;
 static final Set<String>offers=Collections.synchronizedSet(new HashSet<>());static final Map<String,List<String>>signals=new java.util.concurrent.ConcurrentHashMap<>();Handler h=new Handler(Looper.getMainLooper());WebSocket ws;boolean stopping=false;int ref=1,ticks=0;
 public void onCreate(){super.onCreate();channels(this);Notification n=notice("جاري الاتصال…");if(Build.VERSION.SDK_INT>=34)startForeground(10,n,ServiceInfo.FOREGROUND_SERVICE_TYPE_REMOTE_MESSAGING);else startForeground(10,n);connect();h.postDelayed(pulse,25000);h.postDelayed(fallbackSync,2500);}
 Notification notice(String s){PendingIntent p=PendingIntent.getActivity(this,1,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new NotificationCompat.Builder(this,"yoyo_connection_v2").setSmallIcon(R.drawable.ic_heart).setContentTitle("YOYO").setContentText(s).setOngoing(true).setContentIntent(p).setSilent(true).build();}
 void state(boolean v){connected=v;Api.changed(this);((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(10,notice(v?"جاهز لاستقبال رسائلك ومكالماتك":"الاتصال مقطوع — جارٍ إعادة المحاولة"));}
 void connect(){if(stopping||!Prefs.hasProfile(this))return;Api.job(()->{Api.refresh(this);Api.contacts(this);},e->{if(stopping)return;if(e!=null){state(false);h.postDelayed(this::connect,8000);return;}if(ws!=null)ws.cancel();ws=Api.HTTP.newWebSocket(new Request.Builder().url(Api.BASE.replace("https://","wss://")+"/realtime/v1/websocket?apikey="+Api.KEY+"&vsn=1.0.0").build(),new WebSocketListener(){public void onOpen(WebSocket s,Response r){try{JSONArray changes=new JSONArray().put(new JSONObject().put("event","*").put("schema","public").put("table","yoyo_native_events"));JSONObject config=new JSONObject().put("broadcast",new JSONObject().put("self",false)).put("presence",new JSONObject().put("key",Prefs.phone(RealtimeService.this))).put("postgres_changes",changes);send("realtime:yoyo-native","phx_join",new JSONObject().put("config",config).put("access_token",Prefs.get(RealtimeService.this,"token")));}catch(Exception ex){s.cancel();}}
 public void onMessage(WebSocket s,String text){try{JSONObject o=new JSONObject(text);String event=o.optString("event");if(event.equals("phx_reply")&&o.optString("topic").equals("realtime:yoyo-native")){if(o.getJSONObject("payload").optString("status").equals("ok")){h.post(()->state(true));Api.job(()->Api.sync(RealtimeService.this,false),err->{});}else s.cancel();}if(event.equals("postgres_changes")){JSONObject record=o.getJSONObject("payload").getJSONObject("data").optJSONObject("record");if(record!=null)Api.job(()->Api.realtimeRecord(RealtimeService.this,record),err->{if(err!=null)Api.job(()->Api.sync(RealtimeService.this,false),x->{});});}}catch(Exception ignored){}}
 public void onFailure(WebSocket s,Throwable t,Response r){if(ws!=s)return;h.post(()->{state(false);if(!stopping)h.postDelayed(RealtimeService.this::connect,5000);});}public void onClosed(WebSocket s,int c,String r){onFailure(s,new Exception("closed"),null);}});});}
 synchronized void send(String topic,String event,JSONObject payload)throws Exception{if(ws!=null)ws.send(new JSONObject().put("topic",topic).put("event",event).put("payload",payload).put("ref",String.valueOf(ref++)).toString());}
 final Runnable pulse=new Runnable(){public void run(){if(stopping)return;try{send("phoenix","heartbeat",new JSONObject());}catch(Exception ignored){}if(++ticks%2==0)Api.job(()->{Api.refresh(RealtimeService.this);send("realtime:yoyo-native","access_token",new JSONObject().put("access_token",Prefs.get(RealtimeService.this,"token")));Api.sync(RealtimeService.this,false);},e->{});h.postDelayed(this,25000);}};
 final Runnable fallbackSync=new Runnable(){public void run(){if(stopping)return;if(Prefs.hasProfile(RealtimeService.this))Api.job(()->{Api.syncPendingIncoming(RealtimeService.this,true);Api.syncOwnStatuses(RealtimeService.this);Api.syncSignals(RealtimeService.this);},e->{});h.postDelayed(this,4000);}};
 static void channels(Context c){if(Build.VERSION.SDK_INT<26)return;NotificationManager n=(NotificationManager)c.getSystemService(NOTIFICATION_SERVICE);NotificationChannel service=new NotificationChannel("yoyo_connection_v2","اتصال يويو",NotificationManager.IMPORTANCE_LOW);service.setSound(null,null);n.createNotificationChannel(service);NotificationChannel message=new NotificationChannel("yoyo_messages_v4","الرسائل",NotificationManager.IMPORTANCE_HIGH);message.setLockscreenVisibility(Notification.VISIBILITY_PRIVATE);message.enableVibration(true);message.setVibrationPattern(new long[]{0,180,100,180});message.setSound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION),new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_NOTIFICATION).build());n.createNotificationChannel(message);NotificationChannel call=new NotificationChannel("yoyo_calls_v3","المكالمات",NotificationManager.IMPORTANCE_HIGH);call.enableVibration(true);call.setSound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_RINGTONE),new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_NOTIFICATION_RINGTONE).build());n.createNotificationChannel(call);}
 public static void message(Context c,JSONObject p){if(openChat.equals(p.optString("from")))return;channels(c);String from=p.optString("from"),name=EventStore.contact(c,from).optString("name","YOYO");PendingIntent pi=PendingIntent.getActivity(c,from.hashCode(),new Intent(c,ChatActivity.class).putExtra("phone",from).putExtra("name",name),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);String text=p.optString("media").equals("image")?"صورة":p.optString("media").equals("voice")?"رسالة صوتية":p.optString("text");Notification publicVersion=new NotificationCompat.Builder(c,"yoyo_messages_v4").setSmallIcon(R.drawable.ic_heart).setContentTitle("YOYO").setContentText("رسالة جديدة").setAutoCancel(true).setVisibility(NotificationCompat.VISIBILITY_PUBLIC).build();Notification n=new NotificationCompat.Builder(c,"yoyo_messages_v4").setSmallIcon(R.drawable.ic_heart).setContentTitle(name).setContentText(text).setStyle(new NotificationCompat.BigTextStyle().bigText(text)).setContentIntent(pi).setAutoCancel(true).setVisibility(NotificationCompat.VISIBILITY_PRIVATE).setPublicVersion(publicVersion).setPriority(1).build();((NotificationManager)c.getSystemService(NOTIFICATION_SERVICE)).notify(from.hashCode(),n);}
 public static void incoming(Context c,JSONObject p){String call=p.optString("callId");if(System.currentTimeMillis()-p.optLong("ts")>60000||!offers.add(call))return;if(!activeCall.isEmpty()){if(activeOutgoing&&activePeer.equals(p.optString("from"))&&Prefs.phone(c).compareTo(p.optString("from"))>0)return;Api.job(()->Api.send(c,Api.base(c,p.optString("from"),"call_hangup").put("callId",call)),e->{});return;}try{JSONObject log=Api.base(c,p.optString("from"),"call_log").put("id",call).put("text","مكالمة فائتة");EventStore.get(c).save(c,log);Api.changed(c);}catch(Exception ignored){}channels(c);String name=EventStore.contact(c,p.optString("from")).optString("name","YOYO");Intent i=new Intent(c,CallActivity.class).putExtra("mode","incoming").putExtra("phone",p.optString("from")).putExtra("name",name).putExtra("callId",call).putExtra("sdp",p.optString("sdp")).putExtra("offeredAt",p.optLong("ts")).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_SINGLE_TOP);PendingIntent open=PendingIntent.getActivity(c,call.hashCode(),i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);PendingIntent yes=PendingIntent.getActivity(c,(call+"answer").hashCode(),new Intent(i).putExtra("answer",true),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);PendingIntent no=PendingIntent.getService(c,(call+"no").hashCode(),new Intent(c,RealtimeService.class).setAction("reject").putExtra("peer",p.optString("from")).putExtra("callId",call),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification n=new NotificationCompat.Builder(c,"yoyo_calls_v3").setSmallIcon(R.drawable.ic_heart).setContentTitle(name).setContentText("مكالمة صوتية واردة").setCategory(NotificationCompat.CATEGORY_CALL).setPriority(2).setVisibility(NotificationCompat.VISIBILITY_PUBLIC).setContentIntent(open).setFullScreenIntent(open,true).setOngoing(true).setTimeoutAfter(60000).addAction(0,"رد",yes).addAction(0,"رفض",no).build();((NotificationManager)c.getSystemService(NOTIFICATION_SERVICE)).notify(9001,n);Api.job(()->Api.send(c,Api.base(c,p.optString("from"),"call_ringing").put("callId",call)),e->{});}
 public int onStartCommand(Intent i,int f,int start){if(Prefs.hasProfile(this)&&(!connected||ws==null))h.post(this::connect);if(i!=null&&"reject".equals(i.getAction())){String peer=i.getStringExtra("peer"),id=i.getStringExtra("callId");((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).cancel(9001);Api.job(()->Api.send(this,Api.base(this,peer,"call_hangup").put("callId",id)),e->{});}if(i!=null&&"microphone".equals(i.getAction())&&Build.VERSION.SDK_INT>=34)try{startForeground(10,notice("مكالمة يويو قيد الاستخدام"),ServiceInfo.FOREGROUND_SERVICE_TYPE_REMOTE_MESSAGING|ServiceInfo.FOREGROUND_SERVICE_TYPE_MICROPHONE);}catch(Exception ignored){}return START_STICKY;}
 public void onDestroy(){stopping=true;connected=false;h.removeCallbacksAndMessages(null);if(ws!=null)ws.cancel();super.onDestroy();}public IBinder onBind(Intent i){return null;}public static void start(Context c){try{ContextCompat.startForegroundService(c,new Intent(c,RealtimeService.class));}catch(Exception ignored){try{c.startService(new Intent(c,RealtimeService.class));}catch(Exception ignored2){}}}
}
